import type { ConfigPlugin } from 'expo/config-plugins';
import { AndroidConfig, withAndroidManifest } from 'expo/config-plugins';

/**
 * Registers an Android intent filter so links like
 *   https://<host>/products/<handle>
 * open a product directly in the app instead of the browser.
 *
 * Why a config plugin rather than editing AndroidManifest.xml by hand: this
 * project has no android/ directory checked in. The native projects are
 * generated by `expo prebuild`, so any manual edit is destroyed the next time
 * that runs. A plugin is applied during generation, which makes the change
 * reproducible and reviewable as code.
 *
 * App Links (autoVerify) rather than plain deep links: autoVerify asks Android
 * to check /.well-known/assetlinks.json on the host at install time. If it
 * verifies, the OS opens the app with no disambiguation dialog. Without it,
 * Android shows a chooser, which is the difference between a link that feels
 * native and one that does not.
 */
export interface DeepLinkOptions {
  /** Hosts to claim, e.g. ["shop.example.com"] */
  hosts: string[];
  /** Path prefix to claim on those hosts. Defaults to /products. */
  pathPrefix?: string;
}

const withDeepLinks: ConfigPlugin<DeepLinkOptions> = (config, { hosts, pathPrefix = '/products' }) => {
  if (!hosts?.length) {
    throw new Error('[withDeepLinks] `hosts` is required and must not be empty.');
  }

  return withAndroidManifest(config, (mod) => {
    const application = AndroidConfig.Manifest.getMainApplicationOrThrow(mod.modResults);
    const activity = AndroidConfig.Manifest.getMainActivityOrThrow(mod.modResults);

    // Required for an intent filter to survive a cold start from a link.
    activity.$['android:launchMode'] = 'singleTask';

    activity['intent-filter'] = activity['intent-filter'] ?? [];

    // Replace our own filter if it is already present, so repeated prebuilds
    // stay idempotent instead of appending a duplicate every run.
    activity['intent-filter'] = activity['intent-filter'].filter(
      (f: any) => !f?.data?.some?.((d: any) => hosts.includes(d?.$?.['android:host'])),
    );

    activity['intent-filter'].push({
      $: { 'android:autoVerify': 'true' },
      action: [{ $: { 'android:name': 'android.intent.action.VIEW' } }],
      category: [
        { $: { 'android:name': 'android.intent.category.DEFAULT' } },
        { $: { 'android:name': 'android.intent.category.BROWSABLE' } },
      ],
      data: hosts.map((host) => ({
        $: { 'android:scheme': 'https', 'android:host': host, 'android:pathPrefix': pathPrefix },
      })),
    } as any);

    void application;
    return mod;
  });
};

export default withDeepLinks;
