# Generated by Django 5.2.17 on 2026-09-09 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Used to look up the store's token env vars.", unique=True)),
                ('name', models.CharField(max_length=200)),
                ('domain', models.CharField(help_text='e.g. my-shop.myshopify.com', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_gid', models.CharField(help_text='e.g. gid://shopify/Product/123', max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('handle', models.CharField(blank=True, max_length=500)),
                ('vendor', models.CharField(blank=True, max_length=255)),
                ('product_type', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('shopify_updated_at', models.DateTimeField(blank=True, null=True)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('first_synced_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.store')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('cli', 'Management command'), ('api', 'API trigger'), ('webhook', 'Webhook')], default='cli', max_length=20)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('products_created', models.IntegerField(default=0)),
                ('products_updated', models.IntegerField(default=0)),
                ('products_unchanged', models.IntegerField(default=0)),
                ('variants_created', models.IntegerField(default=0)),
                ('variants_updated', models.IntegerField(default=0)),
                ('variants_unchanged', models.IntegerField(default=0)),
                ('rate_limit_backoffs', models.IntegerField(default=0)),
                ('api_requests', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_runs', to='catalog.store')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=20)),
                ('event_type', models.CharField(choices=[('started', 'Sync started'), ('page_fetched', 'Page fetched'), ('rate_limit_backoff', 'Rate limit backoff'), ('product_upserted', 'Product upserted'), ('finished', 'Sync finished'), ('error', 'Error')], max_length=40)),
                ('message', models.CharField(max_length=1000)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('sync_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='catalog.syncrun')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_gid', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('sku', models.CharField(blank=True, max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('inventory_quantity', models.IntegerField(blank=True, null=True)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('first_synced_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['store', 'handle'], name='catalog_pro_store_i_e69e84_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('store', 'shopify_gid'), name='unique_product_per_store'),
        ),
        migrations.AddConstraint(
            model_name='variant',
            constraint=models.UniqueConstraint(fields=('product', 'shopify_gid'), name='unique_variant_per_product'),
        ),
    ]
