# Generated by Django 5.2.17 on 2026-09-26 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaobjectDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text="Shopify metaobject 'type', e.g. demo_pdp_module", max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('shopify_gid', models.CharField(max_length=255)),
                ('storefront_access', models.CharField(default='PUBLIC_READ', help_text="Mirrors MetaobjectDefinition.access.storefront. Must be PUBLIC_READ for the Storefront API to ever see this type's entries.", max_length=20)),
                ('field_definitions', models.JSONField(blank=True, default=list, help_text='As provisioned: [{key, name, type, required, validations}, ...]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metaobject_definitions', to='catalog.store')),
            ],
            options={
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='MetaobjectEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=255)),
                ('shopify_gid', models.CharField(max_length=255)),
                ('fields', models.JSONField(blank=True, default=dict, help_text='key -> value, as set on Shopify')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='catalog.metaobjectdefinition')),
            ],
            options={
                'ordering': ['handle'],
            },
        ),
        migrations.CreateModel(
            name='ProductMetafieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('owner_type', models.CharField(default='PRODUCT', max_length=50)),
                ('metafield_type', models.CharField(help_text='e.g. list.metaobject_reference', max_length=100)),
                ('shopify_gid', models.CharField(max_length=255)),
                ('storefront_access', models.CharField(default='PUBLIC_READ', max_length=20)),
                ('validations', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_metafield_definitions', to='catalog.store')),
            ],
            options={
                'ordering': ['namespace', 'key'],
            },
        ),
        migrations.AddConstraint(
            model_name='metaobjectdefinition',
            constraint=models.UniqueConstraint(fields=('store', 'type'), name='unique_metaobject_definition_per_store'),
        ),
        migrations.AddConstraint(
            model_name='metaobjectentry',
            constraint=models.UniqueConstraint(fields=('definition', 'handle'), name='unique_metaobject_entry_per_definition'),
        ),
        migrations.AddConstraint(
            model_name='productmetafielddefinition',
            constraint=models.UniqueConstraint(fields=('store', 'namespace', 'key', 'owner_type'), name='unique_metafield_definition_per_store'),
        ),
    ]
